# terraform-apply.yaml
name: Terraform Apply
run-name: Terraform Apply by @${{ github.actor }}

on:
  workflow_dispatch: # Manually run
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ca-nakano-jb-tag-test-prd
  PROJECT_NUMBER: 267105866500
  TERRAFORM_VERSION: 1.8.5

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - uses: google-github-actions/auth@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool-test/providers/github-actions-test
        service_account: gitactions-test@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve -no-color